### PR TITLE
fix(lmp): add pair_deepmd_index arg to fix dplr for multiple deepmd pairs

### LINKED ISSUE #4273: issue in using dplr with hybrid/scaled pair_style
When using dplr with hybrid/scaled pair_style to combining two dplr models, fix_dplr can not be used to define all dplr models.
input:

```
pair_style hybrid/scaled &
           v_LAMBDA_i deepmd ini.pb &
           v_LAMBDA_f deepmd fin.pb

pair_coeff *  * deepmd 1
pair_coeff *  * deepmd 2


fix   0 all dplr model ini.pb type_associate 1 4 bond_type 1
fix_modify  0 virial yes
fix   1 all dplr model ini.pb type_associate 1 5 bond_type 1
fix_modify  1 virial yes
```

log.lammps:
```
ERROR: pair_style deepmd should be set before this fix
 (/home/conda/feedstock_root/build_artifacts/deepmd-kit_1707091051406/work/source/lmp/fix_dplr.cpp:144)
Last command: fix   0 all dplr model ini.pb type_associate 1 4 bond_type 1

```

### PR DESCRIPTION
**Pull request by njzjz**
Fix #4273.

## Summary by CodeRabbit

- **New Features**
	- Introduced a new optional keyword `pair_deepmd_index` in the `fix dplr` command for enhanced control in simulations.
	- Updated documentation with clearer instructions and examples for the DPLR model, including training process and simulation setup.

- **Bug Fixes**
	- Improved error handling related to the new `pair_deepmd_index` parameter to ensure proper usage.

- **Documentation**
	- Enhanced descriptions and usability of the DPLR model documentation.

### CODE REVIEW

File: source/lmp/fix_dplr.cpp [hunk 1]
```diff
@@ -62,6 +62,7 @@ FixDPLR::FixDPLR(LAMMPS *lmp, int narg, char **arg)
   size_vector = 3;
   qe2f = force->qe2f;
   xstyle = ystyle = zstyle = NONE;
+  pair_deepmd_index = 0;
```
Comment (wanghan-iapcm) [inline source/lmp/fix_dplr.cpp:65]: should the default be 1?

Comment (njzjz) [reply source/lmp/fix_dplr.cpp:65]: 0 and 1 have different meanings:
- 0: If there is one pair, that pair will be found; if there are two pairs, no pair will be found;
- 1: The first pair is always found.

I feel that "if there are two pairs, no pair will be found" is safer. Users have to explicitly assign an index.

**Review by wanghan-iapcm — APPROVED** [review]
