### PR TITLE
fix(c++): fix NULL type in custom op

### LINKED ISSUE #4749: NULL atom type can not be used with deepmd 3.1.0a0 pth
### Bug summary

NULL atom type can not be used with deepmd 3.1.0a0 pth

### DeePMD-kit Version

v3.1.0a0

### Backend and its version

v3.1.0a0

### How did you download the software?

Offline packages

### Input Files, Running Commands, Error Log, etc.

pair_style hybrid/scaled &
           v_LAMBDA_i deepmd /public/home/fengw/Li_potential/LiFSI_8_EC_80_1:10/sol_li/02.workdir/iter-001/deepmd_ini/model-3/frozen_model.pth /public/home/fengw/Li_potential/LiFSI_8_EC_80_1:10/sol_li/02.workdir/iter-001/deepmd_ini/model-2/frozen_model.pth /public/home/fengw/Li_potential/LiFSI_8_EC_80_1:10/sol_li/02.workdir/iter-001/deepmd_ini/model-0/frozen_model.pth /public/home/fengw/Li_potential/LiFSI_8_EC_80_1:10/sol_li/02.workdir/iter-001/deepmd_ini/model-1/frozen_model.pth out_freq ${THERMO_FREQ} out_file model_devi_ini.out &
           v_LAMBDA_f deepmd /public/home/fengw/Li_potential/LiFSI_8_EC_80_1:10/sol_li/02.workdir/iter-001/deepmd_fin/model-3/frozen_model.pth  &
           v_LAMBDA_f lj/cut 6.000

pair_coeff *  * deepmd 1 O H N S C F Li Li
pair_coeff *  * deepmd 2 O H N S C F Li NULL
pair_coeff *  * lj/cut 0.0    1.0     0.0
pair_coeff *  8 lj/cut 0.0069 2.3370  6.0

Neighbor list info ...
  update: every = 1 steps, delay = 0 steps, check = yes
  max neighbors/atom: 2000, page size: 100000
  master list distance cutoff = 7
  ghost atom cutoff = 7
  binsize = 3.5, bins = 7 7 7
  3 neighbor lists, perpetual/occasional/extra = 3 0 0
  (1) pair deepmd, perpetual
      attributes: full, newton on
      pair build: full/bin/atomonly
      stencil: full/bin/3d
      bin: standard
  (2) pair deepmd, perpetual, copy from (1)
      attributes: full, newton on
      pair build: copy
      stencil: none
      bin: none
  (3) pair lj/cut, perpetual, half/full from (1)
      attributes: half, newton on
      pair build: halffull/newton/tri
      stencil: none
      bin: none
Setting up Verlet run ...
  Unit style    : metal
  Current step  : 0
  Time step     : 0.0005
double free or corruption (!prev)
/public/SLURM/spool/d/job829571/slurm_script: 行 20: 3205933 Aborted                 (核心已转储)lmp_mpi -i lammps.in -v restart 0

### Steps to Reproduce

the command 
pair_coeff *  * deepmd 2 O H N S C F Li NULL
failed

### Further Information, Files, and Links

_No response_

### PR DESCRIPTION
**Pull request by iProzd**
Replaces usage of lmp_list send/recv arrays with new vectors that map indices using fwd_map and synchronize counts via MPI. Updates tensor construction to use these new vectors, improving correctness and flexibility in distributed communication.

## Summary by CodeRabbit

* **Refactor**
  * Message-passing now remaps send lists to actual atoms before building communication tensors, improving consistency for distributed runs.
* **Bug Fixes**
  * Invalid or out-of-range send indices are filtered and counts updated to prevent communication mismatches and related errors.
* **Tests**
  * Added a test covering a type-map scenario with a NULL mapping to exercise the updated handling.

### CODE REVIEW

File: source/api_cc/src/DeepPotPT.cc [hunk 1]
```diff
@@ -10,6 +10,13 @@
 #include "device.h"
 #include "errors.h"
 
+#ifdef USE_MPI
```
Comment (njzjz) [inline source/api_cc/src/DeepPotPT.cc]: This needs to be given in the CMake file. See op
https://github.com/deepmodeling/deepmd-kit/blob/ba8f52e2d9b7d71b36c4b07962868e3dfeda4ddd/source/op/pt/CMakeLists.txt#L34

Comment (njzjz) [reply source/api_cc/src/DeepPotPT.cc]: MPI also needs to be linked, if used.

Comment (njzjz) [reply source/api_cc/src/DeepPotPT.cc]: https://github.com/deepmodeling/deepmd-kit/blob/ba8f52e2d9b7d71b36c4b07962868e3dfeda4ddd/source/op/pt/CMakeLists.txt#L33

File: source/api_cc/src/DeepPotPT.cc [hunk 2]
```diff
@@ -10,6 +10,13 @@
...
+#include <mpi.h>
+#ifdef OMPI_MPI_H
+#include <mpi-ext.h>
```
Comment (njzjz) [inline source/api_cc/src/DeepPotPT.cc]: Not needed.

**Review by njzjz — APPROVED** [review]

**Review by HydrogenSulfate — APPROVED** [review]
LGTM for `source/api_cc/src/DeepPotPD.cc`

**Review by caic99 — APPROVED** [review]

**Comment by link89** [comment]
It looks like this PR is pending by a false positive failed of build machine. Can you rerun those test and see if is PR can be merged? I am looking forward to this issue to be resolved.

**Review by njzjz — APPROVED** [review]
