### PR TITLE
fix: invalid read and write when natom grows

### LINKED ISSUE #3015: [BUG] deepmd::NeighborListData::shuffle_exclude_empty went error when using lammps deposit command
### Bug summary

Lammps stops when turning on the `fix deposit` command together with DP-Pot

### DeePMD-kit Version

2.2.7

### TensorFlow Version

2.9

### How did you download the software?

Built from source

### Input Files, Running Commands, Error Log, etc.

# lammps input
```
variable        TEMP            equal 300.000000


units           metal
boundary        p p f
atom_style      atomic

neighbor        1.0 bin 

box          tilt large
read_data      ./InO-substrate-opt.lmps
change_box   all triclinic
mass            1 114.818
mass            2 15.999
mass            3 69.723 
pair_style      deepmd /data/ch3_202/zhgong/potentials/dp-IO/train-1/frozen_model1.pb /data/ch3_202/zhgong/potentials/dp-IO/train-2/frozen_model2.pb &
                       /data/ch3_202/zhgong/potentials/dp-IO/train-3/frozen_model3.pb /data/ch3_202/zhgong/potentials/dp-IO/train-4/frozen_model4.pb atomic out_freq 100 out_file model_devi.out 
pair_coeff      * *



dump            TRAJ_QUENCH all xyz 100 ./InO-deposition-opt-nvt-300.xyz
dump_modify     TRAJ_QUENCH element In O Ga format line "%2s           %12.6f      %12.6f       %12.6f"

# velocity initialization
velocity all create ${TEMP} 66666 
fix zwalls all wall/reflect zlo EDGE zhi EDGE



# upperlayers - thermostat 
region upperlayers block INF INF INF INF 3 INF
group thermolayers region upperlayers
fix 1 thermolayers nvt temp ${TEMP} ${TEMP} 0.1
# fix 1 thermolayers langevin ${TEMP} ${TEMP} 0.1 587283
# fix 3 thermolayers nve 


# bottomlayers - fixed 
region bottomlayers block INF INF INF INF 0 3
group fixedlayers region bottomlayers
fix 2 fixedlayers setforce 0.0 0.0 0.0
velocity fixedlayers set 0.0 0.0 0.0

# deposition_insert_region - settings
region depo_region block 0 40.47 0 40.47 61.0 63.8
group deposition region depo_region


group  inserted_In empty
group  inserted_O empty
fix 4 inserted_In deposit 800 1 60 12345 region depo_region near 2.4 vz -4.12 -4.12 
fix 5 inserted_O  deposit 1200 2 40 12345 region depo_region near 2.4 vz -11.8 -11.8
fix 6 inserted_In nve
fix 7 inserted_O nve


group mobile_atoms union inserted_In inserted_O thermolayers
compute temperature mobile_atoms temp
compute_modify temperature dynamic/dof yes


thermo_style    custom step temp c_temperature pe ke etotal press atoms
thermo          1

timestep        0.00200
run             80000

```
# Error
```
*** Error in ~lmp_mpi': malloc(): smallbin double linked list corrupted: 0x000090993c528e69 ***
====== Backtrace: =========
/lib64/libc.so.6(+0x7ab54)[0x2b48dec83b54]
/lib64/libc.so.6(+0x7ddf7)[0x2b48dec86df7]
/lib64/libc.so.6(libc malloc+0x4c)[0x2b48dec8910c]
/data/share/apps/gcc/7.4.0/1ib64/libstdc++.so.6( Znwm+0x18)[0x2b48dcof5978]
/data/share/apps/deepmd/2.8-cuda11.3/lib/libdeepmd cc.so( ZN6deepmd16NeighborlistData21shuffle exclude emptyERKSt6vectorTisaliEE+
x278)[0x2b489e3fdod8]
/data/share/apps/deepmd/2.8-cuda11.3/lib/libdeepmd cc.so( ZN6deepmd7Deeppot7computeERdRst6vectorIdsaIdEES5 RKS4 RKS2 TisaIiEEs7 iR
KNS 10InputNlistERKiS7 S7 +0x1c4)[0x2b489e3ef014]
lmp mpi( ZN9LAMMPS NS10PairDeepMD7computeEii+0x191e)[0x92607e]
lmp mpi( ZN9LAMMPS NS6Verlet3runEi+0x662)[0x79e9e2]lmp_mpi(_ZN9LAMMPS NS3Run7commandEipPc+0xa1e)[0xac47ce]
Imp mpi( ZN9LAMMPS NS5Input15command creatorINS 3RunEEEVPNS 6LAMMPSEiPPc+0x26)[0x6f667671mp_mpi(_ZN9LAMMPS NS5Input15execute commandEv+0x78a)[0x6f438a]lmp mpi( ZN9LAMMPS NS5Input4fileEv+0x12b)[0x6f4bob]
1mp mpi(main+0x46)[0x6b73b6]/lib64/libc.so.6(libc start main+0xf5)[0x2b48dec2ac05]lmp_mpi[0x6ebf16]:====== Memory map: =======00400000-01f30gg0 r-xp 00000000 00:29 215798810
/data/share/apps/deepmd/2.0-cuda11.3/bin/1mp_mpi/data/share/apps/deepmd/2.0-cuda11.3/bin/1mp_mpi/data/share/apps/deepmd/2.0-cuda11.3/bin/1mp_mpi
0212f000-02209000 r--p 01b2f000 00:29 21579881002209000-02216000 rw-p 01c09000 00:29 21579881002216000-02220g00 rw-p oogooooo 00:00 0025d000g-50371gge rw-p gggggge 0g:00 0200000000-2004g0gg0 ---p 00gg0g08 00:00 020g40g0g0-2006gggg0 rw-sgggoggoo00:05 2305800:05200600000-2008ggggg rw-sgggggggo299232gg8ggggg-205ggggg rw-sgoggeggg00:05230580000909000:0529923205000000-2052000g0 rw-s205200000-206200000 ---p oogooooo09:0092062gggg0-2064ggggg rw-s09:0523058gggggggg00000000 00:05 2305820640gg0g-2066000g0 rw-s2066ggggg-2068ggggg rw-s2066ggg00 00:05 1019502068gggg0-206a0g0g0 rw-sgoggggg0 00:05 23058
[heap]
/dev/nvidiact1
/dev/nvidia0
/dev/nvidiactl/dev/nvidia0
/dev/nvidiactl/dev/nvidiactl/dev/nvidia-uvm/dev/nvidiactl
```

### Steps to Reproduce

1. prepare the lammps input
2. `lmp_mpi -i input.lammps 1>> lammps.log 2>> lammps.err`

### Further Information, Files, and Links

submitted to @njzjz

### PR DESCRIPTION
**Pull request by Cloudac7**
This PR fixes #3015, which reported an invalid memory read and write when running `fix deposition` in Lammps to add atoms into the system. The issue could not be reproduced when `atomic` was removed from the `pair_style deepmd` line.

As suggested by @njzjz , the possible cause of the bug was the allocation of `stdfsend`, `stdfrecv`, etc., which only happened when `out_each == 1`, set by `atomic` in the `pair_style deepmd` command. Moreover, their size was only determined in the initialization step, based on the initial `natoms`. The valgrind log also supported this hypothesis, as it showed `MPI_Gather` and `MPI_Gatherv` errors in the traceback.

Therefore, we decided to destroy and recreate the memory when `atom->natoms` became larger than `stdfsend`. This should prevent the invalid memory access and resolve the issue.

### CODE REVIEW

**Review by njzjz — APPROVED** [review]

File: source/lmp/pair_deepmd.cpp [hunk 1]
```diff
@@ -783,6 +783,17 @@ void PairDeepMD::compute(int eflag, int vflag) {
           // Gather std_f and tags
           tagint *tag = atom->tag;
           int nprocs = comm->nprocs;
+          int newntotal = atom->natoms;
+          if (newntotal > sizeof(stdfsend)) {
```
Comment (wanghan-iapcm) [inline source/lmp/pair_deepmd.cpp:787]: i am afraid the `sizeof(stdfsend)` is not what you want, see the example below:
```c++
  double aa[10];                                                                
  std::cout << sizeof(aa) << std::endl;  
```
prints
```shell
80
```

**Review by wanghan-iapcm — CHANGES_REQUESTED** [review]

File: source/lmp/pair_deepmd.cpp (hunk 1 above)
Comment (Cloudac7) [reply source/lmp/pair_deepmd.cpp]: As there is no way to get size of a pointer to the array, I just defined a new private parameter `max_nlocal` for `PairDeepMD`. Set default to 0, it would be set to `ntotal` in `init_style` and growing larger when `nlocal` (set to `atom->nloc`) becomes larger than it, to decide whether recreate `stdfsend` etc.

**Review by njzjz — CHANGES_REQUESTED** [review]

File: source/lmp/pair_deepmd.cpp [hunk 2]
```diff
@@ -783,6 +784,18 @@ void PairDeepMD::compute(int eflag, int vflag) {
...
+            max_nlocal = nlocal;
+            memory->destroy(stdfsend);
+            memory->destroy(stdfrecv);
+            memory->destroy(tagsend);
+            memory->destroy(tagrecv);
+            memory->create(stdfsend, nlocal, "deepmd:stdfsendall");
+            memory->create(stdfrecv, nlocal, "deepmd:stdfrecvall");
+            memory->create(tagsend, nlocal, "deepmd:tagsendall");
+            memory->create(tagrecv, nlocal, "deepmd:tagrecvall");
+          }
```
[the remark this answers is not in the document]
Comment (njzjz) [reply source/lmp/pair_deepmd.cpp:798]: btw, I think `all_nlocal` is equal to `atom->natoms`.

[the remark this answers is not in the document]
Comment (Cloudac7) [reply source/lmp/pair_deepmd.cpp:798]: > `nlocal` is just the number in this processor. Here, for MPI communications, we should use the total number of atoms in all processors, i.e. `all_nlocal`.

I see. `all_nlocal`, summed up from all MPI processes, should be used here. And nothing seems to be wrong since I just used only 1 process to do the test in the last test.

**Review by wanghan-iapcm — COMMENTED** [review]
I would recommend changing the name `max_nlocal` -> `stdf_comm_buff_size` to make it more self-explanatory.

File: source/lmp/pair_deepmd.cpp [hunk 3]
```diff
@@ -1279,6 +1292,9 @@ void PairDeepMD::init_style() {
   if (out_each == 1) {
     int ntotal = atom->natoms;
     int nprocs = comm->nprocs;
+    if (ntotal > max_nlocal) {
```
Comment (wanghan-iapcm) [inline source/lmp/pair_deepmd.cpp:1295]: please make sure here the `atom->natoms` gives the total number of atoms in the system, not the natoms per processor.

Comment (njzjz) [reply source/lmp/pair_deepmd.cpp:1295]: https://docs.lammps.org/Developer_atom.html#owned-and-ghost-atoms

Comment (njzjz) [reply source/lmp/pair_deepmd.cpp:1295]: Maybe we should deprecate `all_nlocal` as LAMMPS has computed it for us per documentation.

Comment (Cloudac7) [reply source/lmp/pair_deepmd.cpp:1295]: > please make sure here the `atom->natoms` gives the total number of atoms in the system, not the natoms per processor.

As tested and verified, `atom->natoms` is always the **true** number of systems, regardless of MPI or serius execution. While `all_local` might be 0 in all but one processes, which might make `stdf_comm_buff_size` to be kept on the original `atom->natoms`. To safely make sure no invalid read or write, is it safer to use `atom->natoms` instead of `all_natoms`?

Comment (njzjz) [reply source/lmp/pair_deepmd.cpp:1295]: You are right. It's not safe when using MPI.

Let's directly define `int all_nlocal = atom->natoms`.

https://github.com/deepmodeling/deepmd-kit/blob/e6acacfa5c7dc6a2528d6828ecec187bb85c3806/source/lmp/pair_deepmd.cpp#L724-L725

File: source/lmp/pair_deepmd.cpp [hunk 4]
```diff
@@ -720,7 +721,7 @@ void PairDeepMD::compute(int eflag, int vflag) {
         }
         double min = numeric_limits<double>::max(), max = 0, avg = 0;
         ana_st(max, min, avg, std_f, nlocal);
-        int all_nlocal = 0;
+        int all_nlocal = atom->natoms;
         MPI_Reduce(&nlocal, &all_nlocal, 1, MPI_INT, MPI_SUM, 0, world);
```
Comment (njzjz) [inline source/lmp/pair_deepmd.cpp:725]: why not remove this line

**Review by wanghan-iapcm — APPROVED** [review]
