### PR TITLE
fix bug of model compression training with se_e2_r type descriptor

### LINKED ISSUE #1681: [BUG] something wrong with `TabulateFusionSeRGradGrad`
### Bug summary

Error throw with `TabulateFusionSeRGradGrad`, when compress training a `se_r` model.

`se_a` does not have this issue.

### DeePMD-kit Version

devel with #1680 applied

### TensorFlow Version

2.7

### How did you download the software?

Built from source

### Input Files, Running Commands, Error Log, etc.

```
Traceback (most recent call last):
  File "/home/jz748/anaconda3/envs/dpdev113/lib/python3.9/site-packages/tensorflow/python/client/session.py", line 1380, in _do_call
    return fn(*args)
  File "/home/jz748/anaconda3/envs/dpdev113/lib/python3.9/site-packages/tensorflow/python/client/session.py", line 1363, in _run_fn
    return self._call_tf_sessionrun(options, feed_dict, fetch_list,
  File "/home/jz748/anaconda3/envs/dpdev113/lib/python3.9/site-packages/tensorflow/python/client/session.py", line 1456, in _call_tf_sessionrun
    return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dim of input should be 3
	 [[{{node gradients_1/gradients/filter_type_0/TabulateFusionSeR_grad/TabulateFusionSeRGrad_1_grad/TabulateFusionSeRGradGrad}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jz748/anaconda3/envs/dpdev113/bin/dp", line 33, in <module>
    sys.exit(load_entry_point('deepmd-kit', 'console_scripts', 'dp')())
  File "/home/jz748/codes/deepmd-kit/deepmd/entrypoints/main.py", line 473, in main
    train_dp(**dict_args)
  File "/home/jz748/codes/deepmd-kit/deepmd/entrypoints/train.py", line 106, in train
    _do_work(jdata, run_opt, is_compress)
  File "/home/jz748/codes/deepmd-kit/deepmd/entrypoints/train.py", line 167, in _do_work
    model.train(train_data, valid_data)
  File "/home/jz748/codes/deepmd-kit/deepmd/train/trainer.py", line 514, in train
    run_sess(self.sess, [self.train_op], feed_dict=train_feed_dict,
  File "/home/jz748/codes/deepmd-kit/deepmd/utils/sess.py", line 21, in run_sess
    return sess.run(*args, **kwargs)
  File "/home/jz748/anaconda3/envs/dpdev113/lib/python3.9/site-packages/tensorflow/python/client/session.py", line 970, in run
    result = self._run(None, fetches, feed_dict, options_ptr,
  File "/home/jz748/anaconda3/envs/dpdev113/lib/python3.9/site-packages/tensorflow/python/client/session.py", line 1193, in _run
    results = self._do_run(handle, final_targets, final_fetches,
  File "/home/jz748/anaconda3/envs/dpdev113/lib/python3.9/site-packages/tensorflow/python/client/session.py", line 1373, in _do_run
    return self._do_call(_run_fn, feeds, fetches, targets, options,
  File "/home/jz748/anaconda3/envs/dpdev113/lib/python3.9/site-packages/tensorflow/python/client/session.py", line 1399, in _do_call
    raise type(e)(node_def, op, message)  # pylint: disable=no-value-for-parameter
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dim of input should be 3
	 [[node gradients_1/gradients/filter_type_0/TabulateFusionSeR_grad/TabulateFusionSeRGrad_1_grad/TabulateFusionSeRGradGrad
 (defined at <string>:4273)
]]

Errors may have originated from an input operation.
Input Source operations connected to node gradients_1/gradients/filter_type_0/TabulateFusionSeR_grad/TabulateFusionSeRGrad_1_grad/TabulateFusionSeRGradGrad:
In[0] Const (defined at /home/jz748/codes/deepmd-kit/deepmd/model/ener.py:278)	
In[1] filter_type_0/TabulateFusionSeR/table_info:	
In[2] filter_type_0/Slice:	
In[3] gradients_1/gradients/filter_type_0/Slice_grad/Pad_1_grad/Slice_1 (defined at /home/jz748/codes/deepmd-kit/deepmd/train/trainer.py:381)	
In[4] filter_type_0/TabulateFusionSeR:

Operation defined at: (most recent call last)
>>>   File "/home/jz748/anaconda3/envs/dpdev113/bin/dp", line 33, in <module>
>>>     sys.exit(load_entry_point('deepmd-kit', 'console_scripts', 'dp')())
>>> 
>>>   File "/home/jz748/codes/deepmd-kit/deepmd/entrypoints/main.py", line 473, in main
>>>     train_dp(**dict_args)
>>> 
>>>   File "/home/jz748/codes/deepmd-kit/deepmd/entrypoints/train.py", line 106, in train
>>>     _do_work(jdata, run_opt, is_compress)
>>> 
>>>   File "/home/jz748/codes/deepmd-kit/deepmd/entrypoints/train.py", line 162, in _do_work
>>>     model.build(train_data, stop_batch)
>>> 
>>>   File "/home/jz748/codes/deepmd-kit/deepmd/train/trainer.py", line 317, in build
>>>     self._build_training()
>>> 
>>>   File "/home/jz748/codes/deepmd-kit/deepmd/train/trainer.py", line 381, in _build_training
>>>     apply_op = optimizer.minimize(loss=self.l2_l,
>>> 
>>>   File "/home/jz748/codes/deepmd-kit/deepmd/op/_tabulate_grad.py", line 40, in _tabulate_fusion_se_r_grad_grad_cc
>>>     dz_dy = op_module.tabulate_fusion_se_r_grad_grad(op.inputs[0], op.inputs[1], op.inputs[2], dy, op.inputs[4])
>>> 
>>>   File "<string>", line 4273, in tabulate_fusion_se_r_grad_grad
>>> 

Original stack trace for 'gradients_1/gradients/filter_type_0/TabulateFusionSeR_grad/TabulateFusionSeRGrad_1_grad/TabulateFusionSeRGradGrad':
  File "/home/jz748/anaconda3/envs/dpdev113/bin/dp", line 33, in <module>
    sys.exit(load_entry_point('deepmd-kit', 'console_scripts', 'dp')())
  File "/home/jz748/codes/deepmd-kit/deepmd/entrypoints/main.py", line 473, in main
    train_dp(**dict_args)
  File "/home/jz748/codes/deepmd-kit/deepmd/entrypoints/train.py", line 106, in train
    _do_work(jdata, run_opt, is_compress)
  File "/home/jz748/codes/deepmd-kit/deepmd/entrypoints/train.py", line 162, in _do_work
    model.build(train_data, stop_batch)
  File "/home/jz748/codes/deepmd-kit/deepmd/train/trainer.py", line 317, in build
    self._build_training()
  File "/home/jz748/codes/deepmd-kit/deepmd/train/trainer.py", line 381, in _build_training
    apply_op = optimizer.minimize(loss=self.l2_l,
  File "/home/jz748/anaconda3/envs/dpdev113/lib/python3.9/site-packages/tensorflow/python/training/optimizer.py", line 407, in minimize
    grads_and_vars = self.compute_gradients(
  File "/home/jz748/anaconda3/envs/dpdev113/lib/python3.9/site-packages/tensorflow/python/training/optimizer.py", line 516, in compute_gradients
    grads = gradients.gradients(
  File "/home/jz748/anaconda3/envs/dpdev113/lib/python3.9/site-packages/tensorflow/python/ops/gradients_impl.py", line 169, in gradients
    return gradients_util._GradientsHelper(
  File "/home/jz748/anaconda3/envs/dpdev113/lib/python3.9/site-packages/tensorflow/python/ops/gradients_util.py", line 682, in _GradientsHelper
    in_grads = _MaybeCompile(grad_scope, op, func_call,
  File "/home/jz748/anaconda3/envs/dpdev113/lib/python3.9/site-packages/tensorflow/python/ops/gradients_util.py", line 331, in _MaybeCompile
    return grad_fn()  # Exit early
  File "/home/jz748/anaconda3/envs/dpdev113/lib/python3.9/site-packages/tensorflow/python/ops/gradients_util.py", line 683, in <lambda>
    lambda: grad_fn(op, *out_grads))
  File "/home/jz748/codes/deepmd-kit/deepmd/op/_tabulate_grad.py", line 40, in _tabulate_fusion_se_r_grad_grad_cc
    dz_dy = op_module.tabulate_fusion_se_r_grad_grad(op.inputs[0], op.inputs[1], op.inputs[2], dy, op.inputs[4])
  File "<string>", line 4273, in tabulate_fusion_se_r_grad_grad
  File "/home/jz748/anaconda3/envs/dpdev113/lib/python3.9/site-packages/tensorflow/python/framework/op_def_library.py", line 744, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "/home/jz748/anaconda3/envs/dpdev113/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 3698, in _create_op_internal
    ret = Operation(
  File "/home/jz748/anaconda3/envs/dpdev113/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 2101, in __init__
    self._traceback = tf_stack.extract_stack_for_node(self._c_op)

...which was originally created as op 'gradients/filter_type_0/TabulateFusionSeR_grad/TabulateFusionSeRGrad_1', defined at:
  File "/home/jz748/anaconda3/envs/dpdev113/bin/dp", line 33, in <module>
    sys.exit(load_entry_point('deepmd-kit', 'console_scripts', 'dp')())
[elided 2 identical lines from previous traceback]
  File "/home/jz748/codes/deepmd-kit/deepmd/entrypoints/train.py", line 162, in _do_work
    model.build(train_data, stop_batch)
  File "/home/jz748/codes/deepmd-kit/deepmd/train/trainer.py", line 316, in build
    self._build_network(data)
  File "/home/jz748/codes/deepmd-kit/deepmd/train/trainer.py", line 340, in _build_network
    = self.model.build (self.place_holders['coord'],
  File "/home/jz748/codes/deepmd-kit/deepmd/model/ener.py", line 235, in build
    = self.descrpt.prod_force_virial (atom_ener, natoms)
  File "/home/jz748/codes/deepmd-kit/deepmd/descriptor/se_r.py", line 416, in prod_force_virial
    [net_deriv] = tf.gradients (atom_ener, self.descrpt_reshape)
  File "/home/jz748/anaconda3/envs/dpdev113/lib/python3.9/site-packages/tensorflow/python/ops/gradients_impl.py", line 169, in gradients
    return gradients_util._GradientsHelper(
[elided 2 identical lines from previous traceback]
  File "/home/jz748/anaconda3/envs/dpdev113/lib/python3.9/site-packages/tensorflow/python/ops/gradients_util.py", line 683, in <lambda>
    lambda: grad_fn(op, *out_grads))
  File "/home/jz748/codes/deepmd-kit/deepmd/op/_tabulate_grad.py", line 35, in _tabulate_fusion_se_r_grad_cc
    dy_df = op_module.tabulate_fusion_se_r_grad(op.inputs[0], op.inputs[1], op.inputs[2], dy, op.outputs[0])
  File "<string>", line 4176, in tabulate_fusion_se_r_grad
  File "/home/jz748/anaconda3/envs/dpdev113/lib/python3.9/site-packages/tensorflow/python/framework/op_def_library.py", line 744, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,

...which was originally created as op 'filter_type_0/TabulateFusionSeR', defined at:
  File "/home/jz748/anaconda3/envs/dpdev113/bin/dp", line 33, in <module>
    sys.exit(load_entry_point('deepmd-kit', 'console_scripts', 'dp')())
[elided 4 identical lines from previous traceback]
  File "/home/jz748/codes/deepmd-kit/deepmd/train/trainer.py", line 340, in _build_network
    = self.model.build (self.place_holders['coord'],
  File "/home/jz748/codes/deepmd-kit/deepmd/model/ener.py", line 183, in build
    = self._import_graph_def_from_frz_model(frz_model, feed_dict, return_elements)
  File "/home/jz748/codes/deepmd-kit/deepmd/model/ener.py", line 278, in _import_graph_def_from_frz_model
    return tf.import_graph_def(graph_def, input_map = feed_dict, return_elements = return_elements, name = "")
  File "/home/jz748/anaconda3/envs/dpdev113/lib/python3.9/site-packages/tensorflow/python/util/deprecation.py", line 552, in new_func
    return func(*args, **kwargs)
  File "/home/jz748/anaconda3/envs/dpdev113/lib/python3.9/site-packages/tensorflow/python/framework/importer.py", line 407, in import_graph_def
    return _import_graph_def_internal(
  File "/home/jz748/anaconda3/envs/dpdev113/lib/python3.9/site-packages/tensorflow/python/framework/importer.py", line 520, in _import_graph_def_internal
    _ProcessNewOps(graph)
  File "/home/jz748/anaconda3/envs/dpdev113/lib/python3.9/site-packages/tensorflow/python/framework/importer.py", line 251, in _ProcessNewOps
    for new_op in graph._add_new_tf_operations(compute_devices=False):  # pylint: disable=protected-access
  File "/home/jz748/anaconda3/envs/dpdev113/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 3848, in _add_new_tf_operations
    new_ops = [
  File "/home/jz748/anaconda3/envs/dpdev113/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 3849, in <listcomp>
    self._create_op_from_tf_operation(c_op, compute_device=compute_devices)
  File "/home/jz748/anaconda3/envs/dpdev113/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 3731, in _create_op_from_tf_operation
    ret = Operation(c_op, self)
  File "/home/jz748/anaconda3/envs/dpdev113/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 2101, in __init__
    self._traceback = tf_stack.extract_stack_for_node(self._c_op)
```

### Steps to Reproduce

```sh
cd examples/water/se_e2_r
dp train input.json
dp freeze
dp compress
dp train input.json -f frozen_model_compressed.pb
```

### Further Information, Files, and Links

The error is throw by https://github.com/deepmodeling/deepmd-kit/blob/92230a3a5f78bb863c19a63f85a9a46dfc1fab88/source/op/tabulate_multi_device.cc#L669

### PR DESCRIPTION
**Pull request by denghuilu**
Fix #1681.
And the result of dp train shows the correctness of model compression training:
`dp train input.json -f frozen_model_compressed.pb`
```
(tensorflow_venv) root@iZ8vb672g6x8vab6ywhddcZ:~/deepmd-kit/examples/water/se_e2_r# cat lcurve.out 
#  step      rmse_val    rmse_trn    rmse_e_val  rmse_e_trn    rmse_f_val  rmse_f_trn         lr
      0      9.07e+00    9.24e+00      2.93e-01    2.95e-01      2.86e-01    2.92e-01    5.0e-03
    100      6.94e+00    6.68e+00      1.20e-01    1.19e-01      2.19e-01    2.11e-01    5.0e-03
    200      7.01e+00    7.15e+00      4.73e-02    4.52e-02      2.22e-01    2.26e-01    5.0e-03
    300      7.06e+00    6.93e+00      5.68e-02    5.37e-02      2.23e-01    2.19e-01    5.0e-03
    400      6.80e+00    7.43e+00      2.92e-01    2.91e-01      2.14e-01    2.34e-01    5.0e-03
    500      6.85e+00    6.88e+00      1.78e-01    1.76e-01      2.16e-01    2.17e-01    5.0e-03
```
`dp train input.json -f frozen_model.pb`
```
(tensorflow_venv) root@iZ8vb672g6x8vab6ywhddcZ:~/deepmd-kit/examples/water/se_e2_r# cat lcurve.out 
#  step      rmse_val    rmse_trn    rmse_e_val  rmse_e_trn    rmse_f_val  rmse_f_trn         lr
      0      9.07e+00    9.24e+00      2.93e-01    2.95e-01      2.86e-01    2.92e-01    5.0e-03
    100      7.18e+00    6.85e+00      3.19e-02    3.22e-02      2.27e-01    2.17e-01    5.0e-03
    200      7.14e+00    7.57e+00      1.80e-03    9.59e-05      2.26e-01    2.39e-01    5.0e-03
    300      7.00e+00    7.05e+00      3.32e-01    3.29e-01      2.20e-01    2.22e-01    5.0e-03
    400      7.51e+00    7.99e+00      4.59e-01    4.58e-01      2.36e-01    2.51e-01    5.0e-03
    500      7.88e+00    7.79e+00      2.09e-01    2.06e-01      2.49e-01    2.46e-01    5.0e-03
```

### CODE REVIEW

File: source/op/tabulate_multi_device.cc [hunk 1]
```diff
@@ -666,7 +666,7 @@ class TabulateFusionSeRGradGradOp : public OpKernel {
     const Tensor& dz_dy_dem_tensor	= context->input(context_input_index++);
     const Tensor& descriptor_tensor = context->input(context_input_index++);
     // set size of the sample
-    OP_REQUIRES (context, (dz_dy_dem_tensor.shape().dims() == 3),      errors::InvalidArgument ("Dim of input should be 3"));
+    OP_REQUIRES (context, (dz_dy_dem_tensor.shape().dims() == 2),      errors::InvalidArgument ("Dim of input should be 3"));
```
Comment (njzjz) [inline source/op/tabulate_multi_device.cc:669]:
```suggestion
    OP_REQUIRES (context, (dz_dy_dem_tensor.shape().dims() == 2),      errors::InvalidArgument ("Dim of input should be 2"));
```

**Review by njzjz — CHANGES_REQUESTED** [review]

**Review by njzjz — APPROVED** [review]

**Review by wanghan-iapcm — APPROVED** [review]
