### PR TITLE
fix `TestReadFileToString.readfiletostring`

### LINKED ISSUE #2346: [BUG] test `TestReadFileToString.readfiletostring` may fail
### Bug summary

Sometimes, `TestReadFileToString.readfiletostring` may fail. If a test cannot be passed at any time, we should disable this test.

### DeePMD-kit Version

devel

### TensorFlow Version

2.9.0

### How did you download the software?

Built from source

### Input Files, Running Commands, Error Log, etc.

```
[ RUN      ] TestReadFileToString.readfiletostring
/__w/deepmd-kit/deepmd-kit/source/api_cc/tests/test_read_file_to_string.cc:26: Failure
Expected equality of these values:
  expected_out_string.c_str()
    Which is: "\nH\n\x15o_atom_virial/shape/0\x12\x5" "Const*\x1B\n\x5value\x12\x12" "B\x10\b\x3\x12"
  file_content.c_str()
    Which is: "\nH\n\x15o_atom_virial/shape/0\x12\x5" "Const*\v\n\x5" "dtype\x12\x2" "0\x3*\x1B\n\x5value\x12\x12" "B\x10\b\x3\x12"
With diff:
@@ -1,4 +1,5 @@
 
 H
-\x15o_atom_virial/shape/0\x12\x5" "Const*\x1B
+\x15o_atom_virial/shape/0\x12\x5" "Const*\v
+\x5" "dtype\x12\x2" "0\x3*\x1B
 \x5value\x12\x12" "B\x10\b\x3\x12

[  FAILED  ] TestReadFileToString.readfiletostring (23 ms)
```

### Steps to Reproduce

https://github.com/deepmodeling/deepmd-kit/actions/runs/4270017254/jobs/7433572039

### Further Information, Files, and Links

_No response_

### PR DESCRIPTION
**Pull request by njzjz**
Fix #2346.

### CODE REVIEW

File: source/api_cc/tests/test_read_file_to_string.cc [hunk 1]
```diff
@@ -12,10 +12,8 @@
 
 #include "common.h"
 TEST(TestReadFileToString, readfiletostring) {
-  std::string file_name = "../../tests/infer/deeppot.pbtxt";
-  deepmd::convert_pbtxt_to_pb(file_name, "deeppot.pb");
   std::string file_content;
-  deepmd::read_file_to_string("deeppot.pb", file_content);
+  deepmd::read_file_to_string("../../tests/infer/deeppot.txt", file_content);
   remove("deeppot.pb");
```
Comment (Yi-FanLi) [inline source/api_cc/tests/test_read_file_to_string.cc]:
```suggestion
```

**Review by Yi-FanLi — APPROVED** [review]
That's a reasonable change. The previous test might fail due to the randomness of convert_pbtxt_to_pb. I approve this PR.

**Review by wanghan-iapcm — APPROVED** [review]
